[package]
name = "cir"
version = "0.1.0"
edition = "2021"

[dependencies]
codespan = "0.11"
la-arena = "0.2"
rustc-hash = "1"
smallvec = "1"

[dependencies.dashmap]
version = "4"
features = ["raw-api"]

[dependencies.smol_str]
version = "0.1.21"
default-features = false