[package]
name = "cir-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
codespan = "0.11"
la-arena = "0.2"
peg = "0.7"

[dependencies.cir]
path = "../cir"

[dev-dependencies]
expect-test = "1"
